### ISSUE TITLE
Update manuals week 6

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#112]
### Content
some manuals have not been updated, they need to be fixed so the customer can use them between week 6 and 7

### Feature
- update all manual.md files

### Action plan
- [ ] message_manual.md
- [ ] room_manual.md
- [ ] device_manual.md
- [ ] lots of README.md
