### ISSUE TITLE
SCCLib in JavaScript

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#128]
### Content
There should be a client computer library in javascript. Which is more easily compatible with devices like tablets. 

### Feature
- Write a library in JavaScript.
- It should contain all functionality like the python library
- example webpage with this library GH-116

### Action plan
- [x] Write library
- [x] Test in Angular
- [x] Test in Node
- [x] Publish to npm
