### ISSUE TITLE
Create Sport Heroes Config

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#135]
### Content
For the first escape room the SCILER system will be used for, we will write a config file to find out if the system is able to do all the real things it will have to do

### Feature
A configuration file to use during the Sport Heroes escaper oom

### Action plan
- [ ] analyse Sport Heroes plan
- [ ] create config file
- [ ] update system if something is not possible

**Comment by GwennanS** [comment]
We don't have to make a simon says config!
