### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#16]
### Context
The back-end should be able to process a configurations file and manage an escape room accordingly. This should also be documented in a manual to allow users to easily write a configuration file.

### Feature
The back-end must be able to take in a configuration file in a predefined format.
- The configuration file must contain the settings of an escape room(duration, start event, etc).
- The configuration file must specify the devices needed for the room.
- The configuration file must specify the events that take place in the room.
- Each event in the configuration file must include triggers, conditions and actions to define the order of events.
- The configuration file must specify the reset,  pre- and post-game phases.

### Action plan
- [ ] Write a manual for configuration file about the settings of an escape room(duration, start event, etc).
- [ ] Write a manual for configuration file about specifying the devices needed for the room.
- [ ] Write a manual for configuration file about specifying the events that take place in the room.
- [ ] Write a manual for configuration file about including triggers, conditions and actions to define the order of events.
- [ ] Write a manual for configuration file about specifying the reset,  pre- and post-game phases.

**Comment by IssaHanou** [comment]
this was resolved in GH-50
