### ISSUE TITLE
SIG

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#171]
### Content
The SIG should have a good enough score.

### Feature
- Run SIG and find things to improve
- Improve SIG

### Action plan
- Wait for Week 8 issues to be merged
- [ ] Upload to SIG by the end of the week - Friday 16.00 uur

### TODO
- [ ] simple and short units of code (not too long, not too complex)
- [ ] duplicate code (`hue_lights.py`, `workingConfigTypes.go`, `handler_helper.go`)
- [ ] less parameters/shorter newCommunicator
