### ISSUE TITLE
documentation project

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#173]
### Content
To guaranty maintainability, all code should be documented as clear as possible.  

### Feature
- documentation for back-end, front-end, and scclib

### Action plan
- [ ] scclib: do issue GH-149 
- [x] back-end: do issue GH-174 
- [x] front-end: do issue GH-176
