### ISSUE TITLE
Update report

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#177]
### Content
After handing in the draft and receiving feedback, the report should be updated.

### TODO
- [ ] ethics chapter
- [ ] comments from team
- [ ] comments from JW
- [ ] comments from Taico
- [ ] updating with new information from last week 
     - implementation: config front-end
     - testing: system tests, back-end coverage, cc library?
     - app: infosheet
     - app: config example
     - app: manuals
