### ISSUE TITLE
Instruction can use status as value

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#179]
### Content
Instruction should be able to use a status (of another device)  as value for an instruction

### Feature
- Feature of this issue

### Action plan
- [x] Add new type status
- [x] Fix type checking
- [ ] On action retrieve and send correct status
- [ ] Make an example (with controlboard and hue lights)
