### ISSUE TITLE
Duration test with 20 client computers

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#206]
### Content
Sciler should be able to handle lots of devices for a long period of time without breaking.

### Feature
- 20 client computers should be connected and active to 1 back-end

### Action plan
- [ ] Setup router
- [ ] Write a client computer
- [ ] Start it 20 times
- [ ] Try to break the back-end
