### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#23]
### Content
The back-end should track and manage events.

### Feature
- The back-end must keep track of the events, whether they have been executed and how many times.
- The back-end must be able to mark an event as executed based on input.
- The back-end must be configurable to schedule events based on in-game time, as well as based on a pre-condition from user input.
- The back-end must keep track of events that happen and messages send and received, writing these to a log text file to allow for the debugging of the system.
### Action plan
- [x] create a map from event/device/timer id to list events including all events in which the event/device/timer id is mentioned
- [x] on statuschange, retrieve event list for that status (event/device/timer) and check if any rule is completed
- [x] if so, execute the corresponding actions
- [x] make rules fully functioning in conditions
