### ISSUE TITLE
Create minimal styling for front-end

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#26]
### Content
Although styling is not very important in the initial stages of the project, a minimal styling to improve upon basic HTML should be added in the first week. It would be nice to have a similar styling to M.O.R.S.E.

### Feature
- Add some minimal styling to the front-end
- Use a general css file to do so
- It should be mobile friendly

### Action plan
- [x] Add a button section to the front-end
- [ ] Add a background color to the front-end
- [x] Add a device overview to the front-end (without content)
- [x] Create a standard home-screen-box css styling

**Comment by IssaHanou** [comment]
https://github.com/janwillemm/morse-2/blob/master/public/assets/css/reset.css CSS from M.O.R.S.E.
