### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#37]
### Content
Client computers should be labelled (or allow for that option) so that users can group devices together to trigger events for all 'lamp' devices.

### Feature
- Allow for labelling of devices (through config)

every component has a label in de config, labels get mapped, actions can have {"type": "label", "type_id": }, instructions are sent to all devices and components in label map.

### Todo
- [ ] generete label maps with components
- [ ] add label to action.Execute(handler)
- [ ] add components to action.message in action.Execute(handler)

**Comment by GwennanS** [comment]
in GH-86, a start has been made of implementing this

**Comment by GwennanS** [comment]
what to do with this issue:
- every component has a label in de config, labels get mapped, actions can have {"type": "label", "type_id": <label>}, instructions are send to all devices and components in label map.
- every device has a label, in front-end devices are ordered under the labels, actions with {"type": "label", "type_id": <label>} send the same message to all devices (so all devices need to have the same component to send it too)
