### ISSUE TITLE
Create front-end page for config file submission

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#47]
### Content
Users should be able to submit a configuration file through the front-end. This should check the file completely and show any errors, if no errors appear, the back-end should be ready for using this configuration.

### Feature
- front-end page with file submission and error logs
- errors should be shown all at the same time, not crashing with one error
- there should be a menu on the front-end: 'operator' en 'configuratie' for users to switch
- the menu should collide on mobile device

### Action plan
- [ ] Menu on front-end with two pages: 'operator' and 'configuratie'
- [ ] Menu should collide on mobile - check relevant size
- [ ] Configuratie page should have file submission button and error log
- [ ] Back-end should return all errors at once

### Related issues
GH-22
