### ISSUE TITLE
Improve config

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#50]
### Content
the basic config handling deals with most errors, however, it should be prevented that errors can go uncaught. Each error should be caught and represented in a useful manner so users can easily debug their config.

### Feature
Update condig to be able to handle
- missing json keys
- and/or conditions

### Action plan
- [ ] Can handle missing json keys (all types)
- [ ] Can handle and/or conditions 
- [x] Use Event in Puzzle -> inheritance

### Related issues
GH-22
