### ISSUE TITLE
Test button

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#6]
### Context
Before the start of an escape room, an operator might want to check if all devices work properly.

### Feature
- The front-end must have a general test button for the escape room to see that all devices are functioning and connected.
- Devices must have test function implemented, which can be custom to each device.

### Action plan
- [ ] Define the test function of a device
- [x] Add a test button to the front-end
- [ ] Implement test button functionality calling all devices (through back-end)
