### ISSUE TITLE
Automatic startup program

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#70]
### Content
All raspberry pis should be configured to run all the programs we need for development. 

### Feature
Currently, there are 2 raspberry pis, one running the broker and door, and one running the control board.

### Action plan
- [x] Let raspberry pi 1 run Mosquitto with the `mosquitto.conf` on startup
- [x] Let raspberry pi 1 run client computer script `door.py` on startup
- [x] Let raspberry pi 2 run client computer script `controlboard.py` on startup

**Comment by GwennanS** [comment]
supervisor is being very silly
