### ISSUE TITLE
JSON config error handling

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#76]
### Content
Implement error handling for missing json keys to ensure readable errors are given (not the general ones from json itself.

Allow multiple errors to be returned at once.

### TODO
- [ ] check types, e.g. conditions is map[string]interface not list
- [ ] indiccate stage in error (json, structure, details)
- [ ] demand certain button events: start

### Related issues
GH-50
