### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#77]
### Content
Making start of the report. This mostly concerns checking guidelines to see what should be included and to decide on what to start writing about this week. 

### Action plan
- [x] Check the guidelines and update this issue with more action points.
- [x] include structure in document
- [x] write introduction chapter
- [x] write problem chapter
- [x] write research chapter
- [x] write design chapter
- [x] write implementation chapter
- [x] write testing chapter
- [x] write conclusion
- [x] write recommendations
- [x] include config in appendices
- [x] include pdfs in appendices
- [x] write infosheet
- [x] write sig chapter
