### ISSUE TITLE
The CC-library should be easier to work with

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#92]
### Content
The CC-library should check if an instruction is "test" if so, call the test function of the device.
The CC-library start function should be asynchronous.
The CC-library get_status should accept a dictionary which will be transformed to JSON.

### Feature
Call the test function in case the instruction is "test", then the script of a device doesn't have to check for "test" in the perform_instruction function.

### Action plan
- [x] Check if incoming instruction is "test" if so call test function instead
- [x] Make the library async
- [x] get_status should accept a dictionary
- [x] logger bug should be fixed
- [ ] update example client scripts
